server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: false

logging:
  level:
    root: debug
    org.apache.tomcat: info
    org.apache.tomcat.util.net: warn